services:
  app:
    container_name: go_app
    build:
      context: .
      dockerfile: docker/dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - air-cache:/go/pkg/mod
    
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: pg_db
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    container_name: db_migrate
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    env_file:
      - .env
    entrypoint:
      [
        "sh", "-c",
        "migrate -path=/migrations -database=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE} up"
      ]
  migrate-down:
    image: migrate/migrate
    container_name: db_migrate_down
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    env_file:
      - .env
    entrypoint:
      [
        "sh", "-c",
        "migrate -path=/migrations -database=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE} down 1"
      ]

    

volumes:
  pgdata:
  air-cache:
